// כל הטקסטים של הממשק במקום אחד

export const strings = {
  appName: "פרלקס",
  settingsTitle: "העדפות",

  feed: {
    endOfFeed: "סיימת לעכשיו",
    endOfFeedHint: "הפיד מתעדכן בערך כל חצי שעה. משכו למטה לרענון.",
    updatedAt: (t: string) => `עודכן ${t}`,
    empty: "אין ידיעות שמתאימות לבחירה שלך כרגע.",
    loading: "טוענים את החדשות…",
    loadFailed: "לא הצלחנו להוריד את החדשות. בדקו את החיבור ונסו שוב.",
    offline: "אין חיבור. מוצג העדכון האחרון שנשמר.",
    retry: "נסו שוב",
  },

  story: {
    notFound: "הידיעה כבר לא זמינה. ייתכן שעברו יותר מ-48 שעות.",
    signals: "כמה אפשר לסמוך על זה?",
    signalsHint: "לחצו על סימן להסבר ולשאלה שכדאי לשאול.",
    leanPending: "נטיית הקהל של המקורות עדיין נבדקת, ולכן פס הקשת עוד לא מוצג.",
    howTheyWrote: "איך כתבו על זה",
    howTheyWroteHint: "השוו בין הכותרות: מה כל אחד הדגיש ומה השמיט? תגובות הגולשים נמצאות בתחתית כל כתבה באתר המקור.",
    howTheyWroteLeanHint: "הנקודה הצבעונית: נטיית הקהל של המקור. תגובות הגולשים נמצאות בתחתית כל כתבה באתר המקור.",
    readFull: "לכתבה ולתגובות הגולשים",
    sourceProfile: "פרופיל המקור",
    reportError: "דווח על טעות",
    perspectives: "נקודות מבט",
    viewpointsTitle: "מה אומרים על זה",
    viewpointsHint: "עמדות שעולות בדיון הציבורי על נושאים כאלה. לא ציטוטים של אנשים אמיתיים, ואף אחת מהן לא בהכרח נכונה.",
    checkPrefix: "מה כדאי לבדוק:",
    aiGenerated: "נוצר ע\"י AI",
    quotesTitle: "מה אמרו בכותרות",
    via: (source: string) => (source ? `דרך ${source}` : ""),
    reflection: "מה חסר כאן כדי להחליט?",
    copyrightNote: "מוצגים כותרת ותקציר קצר בלבד. הכתבה המלאה באתר המקור.",
  },

  lean: { right: "ימין", center: "מרכז", left: "שמאל", unknown: "לא נבדק" },

  ask: {
    title: "רוצה להבין יותר?",
    hint: "בחרו שאלה. היא תיפתח ב-Gemini יחד עם הכותרת והקישור לידיעה.",
    a11yHint: "פותח את Gemini עם השאלה, הכותרת והקישור",
    // כשעוד לא נוצרו שאלות מתוך הידיעה: כפתור אחד כללי, לא רשימה קבועה
    general: "הסבר לי את הידיעה ואת הרקע שלה",
  },

  source: {
    notFound: "המקור לא נמצא.",
    site: "אתר",
    owner: "בעלות",
    funding: "מימון",
    pressCouncil: "חבר במועצת העיתונות",
    corrections: "מדיניות תיקונים",
    ifcn: "חתום על קוד העקרונות של IFCN",
    audienceLean: "נטיית קהל",
    evidence: "מקורות למידע",
    evidenceLink: "מקור",
    leanNote: "נטיית הקהל: מי קורא את כלי התקשורת, לפי סקר או מחקר. לא קביעה על התוכן.",
    unknown: "עדיין לא נבדק",
    yes: "כן",
    no: "לא",
    note: "המידע כאן הוא עובדות עם קישור לראיה. אנחנו לא מדרגים כלי תקשורת כאמינים או לא אמינים.",
  },

  onboarding: {
    welcome: "ברוכים הבאים לפרלקס",
    intro: "חדשות מהארץ ומהעולם, עם סימני אמינות שקופים והשוואה בין כלי תקשורת מכל הקשת.",
    interestsTitle: "מה מעניין אותך?",
    regionsTitle: "מאיפה החדשות?",
    notificationsTitle: "עדכונים",
    notificationsBody: "שלוש תזכורות ביום (בוקר, צהריים, ערב). אפשר לשנות בכל רגע בהעדפות.",
    next: "המשך",
    back: "חזרה",
    done: "בואו נתחיל",
    pickOne: "בחרו לפחות תחום אחד",
  },

  settings: {
    interests: "תחומי עניין",
    regions: "מקורות",
    translation: "שפת הכתבות",
    translationAuto: "תרגום אוטומטי לעברית",
    translationOriginal: "שפת המקור",
    translationSoon: "התרגום יתווסף בגרסה הבאה.",
    notifications: "התראות",
    notificationsSoon: "ההתראות יופעלו בגרסה הבאה. הבחירה שלך נשמרת.",
    about: "מידע",
    methodology: "איך אנחנו מדרגים",
    privacy: "מדיניות פרטיות",
    contact: "יצירת קשר ודיווח על טעות",
    version: (v: string) => `גרסה ${v}`,
  },

  regions: { il: "מהארץ", world: "מהעולם", both: "שניהם" },
  notifications: { morning: "בוקר (07:30)", noon: "צהריים (13:00)", evening: "ערב (20:00)" },
  allCategories: "הכל",
} as const;
